Team-Omechu/Omechu-server

.gitignore
.vscode/settings.json
package-lock.json
package.json
src/db.config.js
src/index.js

#1 
- `src/` 디렉토리 생성 및 내부 구조 정리
- `controllers/` : 요청 처리 핸들러
- `services/` : 비즈니스 로직
- `repositories/` : DB 쿼리 담당
- `dtos/` : 요청/응답 데이터 포맷
- 기본 서버 진입점 `src/index.js` 생성
- `db.config.js` : DB 연결 설정 파일 생성
- `errors.js` : 공통 에러 정의 파일 생성
- `.env` 파일 생성 및 환경변수 분리
- `.gitignore` 설정 (`node_modules`, `.env` 등 제외)
- `.vscode/settings.json` 설정
- `package.json` → `"type": "module"` 설정
어떤 변경 사항이 있나요?

[Init/#1] : 프로젝트 초기 생성 및 설정

---

src/index.js

#13 
- 로그인 API 개발
어떤 변경 사항이 있나요?

[Init] 에러 미들웨어 추가

---

prisma/schema.prisma
src/controllers/auth.controller.js
src/controllers/login.controller.js
src/errors.js
src/index.js
src/repositories/login.repository.js
src/services/login.service.js

#23
- 로그인 API 개발
어떤 변경 사항이 있나요?

[Feat] 로그인 API 구현 완료

---

src/index.js

#25  
- 사용자 세션 검증 미들웨어 설정
어떤 변경 사항이 있나요?

[Init] 사용자 세션 검증 미들웨어 설정

---

prisma/schema.prisma
src/controllers/addReview.controller.js
src/controllers/login.controller.js
src/dtos/addReview.dto.js
src/errors.js
src/index.js
src/repositories/addReview.repository.js
src/services/addReview.service.js

#27 
- 리뷰 등록하기 API 구현 
어떤 변경 사항이 있나요?

[Feat] 리뷰 등록하기 API 구현 

---

prisma/schema.prisma
src/controllers/getReview.controller.js
src/dtos/getReview.dto.js
src/errors.js
src/index.js
src/repositories/getReview.repository.js
src/services/getReview.service.js

#31 
- 리뷰 가져오기 API 구현 
어떤 변경 사항이 있나요?

[Feat] 리뷰 가져오기 API 구현 

---

backend/src/index.js

#47
- CORS 에러 처리
어떤 변경 사항이 있나요?

[Init] CORS 에러 처리

---

backend/src/controllers/mypage.controller.js
backend/src/dtos/mypage.dto.js
backend/src/errors.js
backend/src/index.js
backend/src/repositories/mypage.repository.js
backend/src/services/mypage.service.js
test.txt

#187 
- 마이페이지 관련 모든 사항
어떤 변경 사항이 있나요?
https://www.notion.so/1fbcea13f40180a7a5e6cfaa7d1e4dec?source=copy_link
작업 참조문서

[feat] 마이페이지 및 찜 기능

---

backend/src/controllers/like.controller.js

#73 
- 좋아요 기능 swagger 문서 수정
어떤 변경 사항이 있나요?

[Refactor] 좋아요 기능 swagger 문서 수정

---

backend/src/controllers/menu.controller.js

#76
- swagger에서 session 제거
어떤 변경 사항이 있나요?
""

recommendmenu swagger 수정

---

backend/prisma/schema.prisma
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/index.js
backend/src/repositories/restaurant.repository.js

#89 
- repre_menu 관련 버그 수정, cors 관련 코드 추가
어떤 변경 사항이 있나요?
- [ O ] 버그 수정

bug fixed and configure cookie settings for CORS and production security

---

backend/src/controllers/reportReveiw.controller.js
backend/src/errors.js
backend/src/index.js
backend/src/repositories/reportReview.repository.js
backend/src/services/reportReview.service.js

#99 
- 리뷰 신고하기 API 구현
어떤 변경 사항이 있나요?

[Feat] 리뷰 신고하기 API 구현

---

backend/src/controllers/restaurant.controller.js
backend/src/repositories/menu.repository.js
backend/src/repositories/restaurant.repository.js

#109 
- 구글맵 평점, 리뷰 수 가져오기
- [o] 새로운 기능 추가

구글맵 평점, 리뷰 수 가져오기

---

backend/src/controllers/mypage.controller.js
backend/src/dtos/mypage.dto.js
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/index.js
backend/src/services/mypage.service.js

#187 
- 마이페이지들 동작하게하기
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가

[Refactor]

---

backend/src/controllers/kakao.controller.js
backend/src/dtos/kakao.dto.js
backend/src/index.js
backend/src/repositories/user.repository.js
backend/src/services/kakao.service.js

#78
- 카카오 로그인 구현
어떤 변경 사항이 있나요?

[feature] 카카오 로그인 구현

---

backend/src/controllers/user.controller.js
backend/src/dtos/user.dto.js
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/repositories/user.repository.js

#119
- state -> exercise로 모두 수정
- allergy, prefer입력시 초기화 후 추가
어떤 변경 사항이 있나요?

[refactor] 로그인 온보딩 API 수정

---

backend/src/controllers/mukburim.statistics.controller.js
backend/src/controllers/recommend.management.controller.js
backend/src/dtos/mypage.dto.js
backend/src/errors.js
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/index.js
backend/src/repositories/mukburim.statistics.repository.js
backend/src/repositories/mypage.repository.js
backend/src/repositories/recommend.management.repository.js
backend/src/services/mukburim.statistics.service.js
backend/src/services/recommend.management.service.js

#187 
- 먹부림 및 매뉴 추천 목록 기능 추가, DTO 개선
어떤 변경 사항이 있나요?

[Feat] 먹부림 및 매뉴 추천 목록 기능 추가, DTO 개선

---

backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/index.js

#55
- /auth/reset-passwd -> /reset-passwd
어떤 변경 사항이 있나요?

[refactor] reset-passwd url 수정

---

backend/src/controllers/getRestaurant.controller.js
backend/src/controllers/mypage.controller.js
backend/src/dtos/mypage.dto.js
backend/src/errors.js
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js
backend/src/index.js
backend/src/repositories/mypage.repository.js
backend/src/services/mypage.service.js

#122 
- 내가 작성한 맛집 정보 조회하기 API 수정
어떤 변경 사항이 있나요?

[Fix] 내가 등록한 맛집 조회 API 수정

---

backend/src/controllers/auth.controller.js
backend/src/dtos/auth.dto.js
backend/src/generated/prisma/edge.js
backend/src/generated/prisma/index.js

#133 
- 로그인 API 개발
어떤 변경 사항이 있나요?

[refactor] 회원가입 토큰으로 변경

---

backend/src/controllers/kakao.controller.js
backend/src/services/kakao.service.js

#139
-카카오 로그인 토큰으로 변경
어떤 변경 사항이 있나요?

[refactor] 카카오 로그인 토큰으로 변경

---

backend/src/controllers/suggestions.controller.js
backend/src/errors.js
backend/src/index.js
backend/src/repositories/suggestions.repository.js
backend/src/services/suggestions.service.js

#148
- 메뉴 자동완성 API 구현 완료
어떤 변경 사항이 있나요?

[Feat] 메뉴 자동완성 API 구현 완료

---

backend/src/controllers/getSearchRestaurant.controller.js
backend/src/dtos/getSearchRestaurant.dto.js
backend/src/repositories/getSearchRestaurant.repository.js

#128 
- 맛집 가져오기 API 수정 완료
어떤 변경 사항이 있나요?

[Refactor] 맛집 가져오기 API 수정 완료

---

backend/src/controllers/mypage.controller.js
backend/src/errors.js
backend/src/index.js
backend/src/repositories/mypage.repository.js
backend/src/services/mypage.service.js

#187 
-  찜 삭제 기능 추가
- 409에러 추가
어떤 변경 사항이 있나요?

[Feature] 찜 삭제 기능 추가, 409 에러 추가

---

backend/src/controllers/menu.controller.js
backend/src/index.js
backend/src/repositories/menu.repository.js
backend/src/services/menu.service.js

#174
랜덤추천구현
어떤 변경 사항이 있나요?
새로운 기능 추가

메뉴 랜덤 추천 기능 구현

---

backend/src/controllers/user.controller.js

#179
- complete오류 수정
어떤 변경 사항이 있나요?

[fix] complete오류 수정

---

backend/src/controllers/auth.controller.js

#179
- 회원가입 API 수정
어떤 변경 사항이 있나요?

[fix] 회원가입 API 수정

---

backend/src/controllers/passwordReset.controller.js
backend/src/services/passwordReset.service.js

#181
- 비밀번호 수정 api수정
어떤 변경 사항이 있나요?

[refactor] 비밀번호 수정 api수정
